# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_0.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1016, 642)
        MainWindow.setStyleSheet("background-color:    rgb(147, 147, 147);\n"
"color: rgb(0, 255, 17);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 600, 981, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 30, 331, 311))
        self.groupBox_2.setObjectName("groupBox_2")
        self.config_path = QtWidgets.QLineEdit(self.groupBox_2)
        self.config_path.setGeometry(QtCore.QRect(10, 50, 291, 24))
        self.config_path.setStyleSheet("background-color:    rgb(255, 255, 255);\n"
"color: rgb(0, 255, 17);")
        self.config_path.setObjectName("config_path")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label.setObjectName("label")
        self.loadconf_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.loadconf_btn.setGeometry(QtCore.QRect(10, 80, 80, 24))
        self.loadconf_btn.setStyleSheet("background-color: rgb(44, 44, 44);\n"
"color: rgb(4, 255, 0);\n"
"")
        self.loadconf_btn.setObjectName("loadconf_btn")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 121, 16))
        self.label_2.setObjectName("label_2")
        self.saveconfig_path = QtWidgets.QLineEdit(self.groupBox_2)
        self.saveconfig_path.setGeometry(QtCore.QRect(10, 140, 291, 24))
        self.saveconfig_path.setStyleSheet("background-color:    rgb(255, 255, 255);\n"
"color: rgb(0, 255, 17);")
        self.saveconfig_path.setObjectName("saveconfig_path")
        self.saveconf_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.saveconf_btn.setGeometry(QtCore.QRect(10, 170, 80, 24))
        self.saveconf_btn.setStyleSheet("background-color: rgb(44, 44, 44);\n"
"color: rgb(4, 255, 0);\n"
"")
        self.saveconf_btn.setObjectName("saveconf_btn")
        self.autoconf_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.autoconf_btn.setGeometry(QtCore.QRect(110, 200, 80, 24))
        self.autoconf_btn.setStyleSheet("background-color: rgb(44, 44, 44);\n"
"color: rgb(7, 255, 226);\n"
"")
        self.autoconf_btn.setObjectName("autoconf_btn")
        self.launch_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.launch_btn.setGeometry(QtCore.QRect(110, 260, 80, 24))
        self.launch_btn.setStyleSheet("background-color: rgb(44, 44, 44);\n"
"color: rgb(7, 255, 226);\n"
"")
        self.launch_btn.setObjectName("launch_btn")
        self.update_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.update_btn.setGeometry(QtCore.QRect(110, 230, 80, 24))
        self.update_btn.setStyleSheet("background-color: rgb(44, 44, 44);\n"
"color: rgb(7, 255, 226);\n"
"")
        self.update_btn.setObjectName("update_btn")
        self.ServerStatus = QtWidgets.QGroupBox(self.centralwidget)
        self.ServerStatus.setGeometry(QtCore.QRect(10, 350, 331, 231))
        self.ServerStatus.setObjectName("ServerStatus")
        self.label_3 = QtWidgets.QLabel(self.ServerStatus)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.label_3.setObjectName("label_3")
        self.status = QtWidgets.QLabel(self.ServerStatus)
        self.status.setGeometry(QtCore.QRect(60, 40, 161, 16))
        self.status.setStyleSheet("background-color:  rgb(81, 81, 81);\n"
"color: rgb(255, 0, 4);\n"
"")
        self.status.setObjectName("status")
        self.con_btn = QtWidgets.QPushButton(self.ServerStatus)
        self.con_btn.setGeometry(QtCore.QRect(110, 200, 80, 24))
        self.con_btn.setStyleSheet("background-color: rgb(44, 44, 44);\n"
"color: rgb(7, 255, 226);\n"
"")
        self.con_btn.setObjectName("con_btn")
        self.check_btn = QtWidgets.QPushButton(self.ServerStatus)
        self.check_btn.setGeometry(QtCore.QRect(230, 30, 80, 24))
        self.check_btn.setStyleSheet("background-color: rgb(44, 44, 44);\n"
"color: rgb(7, 255, 226);\n"
"")
        self.check_btn.setObjectName("check_btn")
        self.username_inp = QtWidgets.QLineEdit(self.ServerStatus)
        self.username_inp.setGeometry(QtCore.QRect(10, 90, 311, 24))
        self.username_inp.setStyleSheet("background-color:    rgb(255, 255, 255);\n"
"color: rgb(0, 255, 17);")
        self.username_inp.setObjectName("username_inp")
        self.password_inp = QtWidgets.QLineEdit(self.ServerStatus)
        self.password_inp.setGeometry(QtCore.QRect(10, 150, 311, 24))
        self.password_inp.setStyleSheet("background-color:    rgb(255, 255, 255);\n"
"color: rgb(0, 255, 17);")
        self.password_inp.setObjectName("password_inp")
        self.label_4 = QtWidgets.QLabel(self.ServerStatus)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.ServerStatus)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.label_5.setObjectName("label_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(340, 30, 661, 551))
        self.groupBox.setObjectName("groupBox")
        self.terminalBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.terminalBrowser.setGeometry(QtCore.QRect(10, 30, 641, 511))
        self.terminalBrowser.setStyleSheet("background-color:  rgb(70, 70, 70);\n"
"color: rgb(60, 255, 0);")
        self.terminalBrowser.setObjectName("terminalBrowser")
        self.send_btn = QtWidgets.QPushButton(self.groupBox)
        self.send_btn.setGeometry(QtCore.QRect(800, 500, 101, 24))
        self.send_btn.setStyleSheet("background-color: rgb(44, 44, 44);\n"
"color: rgb(4, 255, 0);\n"
"")
        self.send_btn.setAutoDefault(True)
        self.send_btn.setObjectName("send_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BigBrother v.1.0 || (c)by BlackLeakz"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Settings"))
        self.label.setText(_translate("MainWindow", "Config - path:"))
        self.loadconf_btn.setText(_translate("MainWindow", "Load"))
        self.label_2.setText(_translate("MainWindow", "Save Config - path:"))
        self.saveconf_btn.setText(_translate("MainWindow", "Save"))
        self.autoconf_btn.setText(_translate("MainWindow", "AutoConf"))
        self.launch_btn.setText(_translate("MainWindow", "Launch"))
        self.update_btn.setText(_translate("MainWindow", "Update"))
        self.ServerStatus.setTitle(_translate("MainWindow", "Server - Status"))
        self.label_3.setText(_translate("MainWindow", "Status: "))
        self.status.setText(_translate("MainWindow", "Offline"))
        self.con_btn.setText(_translate("MainWindow", "Connect"))
        self.check_btn.setText(_translate("MainWindow", "Check"))
        self.label_4.setText(_translate("MainWindow", "Username"))
        self.label_5.setText(_translate("MainWindow", "Password"))
        self.groupBox.setTitle(_translate("MainWindow", "Console"))
        self.send_btn.setText(_translate("MainWindow", "Send"))
